/**
 * Supabase client factories.
 *
 * Two clients are exported:
 *
 *   - `getSupabaseAdmin()` — service-role key, full access, bypasses RLS.
 *     Used by every server-side path: build-time content loaders, API routes,
 *     Astro Actions, and the migration script. Never imported from .astro
 *     components or browser-bundled code.
 *
 *   - `getSupabaseAnon()` — anon key, sees zero rows today (RLS deny-all).
 *     Reserved for future browser use; included so adding policies later
 *     is a one-line change rather than a refactor.
 *
 * Both are lazy singletons: importing this module doesn't open a connection,
 * so the build doesn't crash when env vars are missing in CI on a clean
 * install. The first call to `getSupabaseAdmin()` validates the env and
 * caches the client.
 *
 * The service-role key is read from `process.env` only — never via
 * `import.meta.env` — so Vite cannot inline it into a client bundle by
 * accident. `src/env.d.ts` deliberately omits `SUPABASE_SERVICE_ROLE_KEY`
 * for the same reason.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';

let _admin: SupabaseClient | undefined;
let _anon: SupabaseClient | undefined;

function readEnv(name: string, value: string | undefined): string {
  if (!value || value.trim() === '') {
    throw new Error(
      `Supabase env var ${name} is required but unset. ` +
        `Set it in .env (local) or your host's secret store (Vercel project settings).`,
    );
  }
  return value.trim();
}

/**
 * Server-only Supabase client with the service-role key. Bypasses RLS.
 * NEVER import this from a `.astro` component, hydrated script, or anything
 * that ships to the browser.
 *
 * Env vars are read from `process.env` first (works for Node scripts,
 * production deploys, and tsx-launched migration scripts) and fall back to
 * `import.meta.env` (where Astro dev / Vite loads `.env`).
 *
 * Vite only inlines `VITE_*`-prefixed variables into client bundles, so the
 * service-role key cannot accidentally leak even if `import.meta.env` is
 * referenced — but the TS `ImportMetaEnv` interface still omits the key
 * to catch any attempt at compile time.
 */
export function getSupabaseAdmin(): SupabaseClient {
  if (_admin) return _admin;

  const url = readEnv(
    'SUPABASE_URL',
    process.env.SUPABASE_URL ?? (import.meta.env.SUPABASE_URL as string | undefined),
  );
  const key = readEnv(
    'SUPABASE_SERVICE_ROLE_KEY',
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ((import.meta.env as any).SUPABASE_SERVICE_ROLE_KEY as string | undefined),
  );

  _admin = createClient(url, key, {
    auth: {
      // Server-side use: don't try to persist or refresh user sessions.
      persistSession: false,
      autoRefreshToken: false,
    },
    db: { schema: 'public' },
  });
  return _admin;
}

/**
 * Anon-key client. Currently sees zero rows because RLS is enabled with no
 * policies. Exported so that policies-and-anon-reads can be added later
 * without rewriting imports.
 */
export function getSupabaseAnon(): SupabaseClient {
  if (_anon) return _anon;

  const url = readEnv(
    'SUPABASE_URL',
    (import.meta.env.SUPABASE_URL as string | undefined) ?? process.env.SUPABASE_URL,
  );
  const key = readEnv(
    'SUPABASE_ANON_KEY',
    (import.meta.env.SUPABASE_ANON_KEY as string | undefined) ?? process.env.SUPABASE_ANON_KEY,
  );

  _anon = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
    db: { schema: 'public' },
  });
  return _anon;
}

/**
 * Database row types — generated by hand to match the SQL in
 * supabase/migrations/0001_init.sql. Worth replacing with `supabase gen
 * types typescript` output once we grow more tables, but for seven tables
 * the manual definition is clearer than generated noise.
 */
export type ContentCategory = 'DevOps' | 'Cloud' | 'AI' | 'Security';
export type ContentDifficulty = 'Beginner' | 'Intermediate' | 'Advanced';
export type PublishStatus = 'draft' | 'published';

export interface BlogPostRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  pub_date: string; // ISO date string
  author: string;
  category: ContentCategory;
  tags: string[];
  image: string | null;
  status: PublishStatus;
  body: string;
  created_at: string;
  updated_at: string;
}

export interface PracticeTestRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: ContentCategory;
  difficulty: ContentDifficulty;
  time_limit: number | null;
  passing_score: number;
  tags: string[];
  status: PublishStatus;
  body: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  pub_date: string;
  author: string;
  category: ContentCategory;
  difficulty: ContentDifficulty;
  tags: string[];
  technologies: string[];
  image: string | null;
  source_url: string | null;
  status: PublishStatus;
  body: string;
  created_at: string;
  updated_at: string;
}

export interface CourseRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: ContentCategory;
  difficulty: ContentDifficulty;
  tags: string[];
  status: PublishStatus;
  modules: unknown; // JSONB — validated by Zod at the manager boundary
  created_at: string;
  updated_at: string;
}

export interface SettingsRow {
  singleton: true;
  enable_presentations: boolean;
  enable_videos: boolean;
  updated_at: string;
}

export interface ContactMessageRow {
  id: string;
  received_at: string;
  ip: string | null;
  user_agent: string | null;
  read: boolean;
  first_name: string;
  last_name: string;
  email: string;
  dial_code: string;
  mobile: string;
  country: string;
  message: string;
}

export interface AdminSessionRow {
  id: string;
  data: unknown; // JSONB — Astro session payload
  expires_at: string;
  updated_at: string;
}
